### ISSUE TITLE
Upgrade for PHP8.x / SSv5 (and Cloudinary PHP package v2)

### ISSUE THREAD

**Issue by lars-lemon8** [Level51/silverstripe-cloudinary#3]
Love this gem of a module.

Are you guys considering doing an upgrade to SSv5 / PHP8.x or is it going to be put out to pasture?   
This also required an upgrade to cloudinary/cloudinary_php version 2.

**Comment by JZubero** [comment]
Hi Lars. Glad our module comes in handy for you. At the moment the upgrade is not a priority for us since exclusively included in ss4/php7.x projects currently. PR welcome though :innocent:

**Comment by lars-lemon8** [comment]
Hi Julian,

https://github.com/Level51/silverstripe-cloudinary/pull/4
